version: '3.9'

services:
  db:
    image: postgres:15.4
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

